# Generated by Django 4.2 on 2025-11-20 13:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Colegio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('direccion', models.CharField(blank=True, max_length=255)),
                ('telefono', models.CharField(blank=True, max_length=50)),
                ('horario_entrada', models.TimeField(blank=True, null=True)),
                ('horario_salida', models.TimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Conductor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(max_length=20, unique=True)),
                ('nombre', models.CharField(max_length=255)),
                ('telefono', models.CharField(blank=True, max_length=50)),
                ('numero_licencia', models.CharField(blank=True, max_length=100)),
                ('tipo_licencia', models.CharField(blank=True, max_length=50)),
                ('fecha_vencimiento_licencia', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(max_length=20, unique=True)),
                ('nombre', models.CharField(max_length=255)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('direccion', models.CharField(blank=True, max_length=255)),
                ('telefono', models.CharField(blank=True, max_length=50)),
                ('nombre_apoderado', models.CharField(blank=True, max_length=255)),
                ('telefono_apoderado', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Furgon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patente', models.CharField(max_length=50, unique=True)),
                ('modelo', models.CharField(blank=True, max_length=100)),
                ('anio', models.PositiveIntegerField(blank=True, null=True)),
                ('capacidad_maxima', models.PositiveIntegerField(default=20)),
                ('capacidad_actual', models.PositiveIntegerField(default=0)),
                ('estado_revision_tecnica', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo'), ('mantenimiento', 'En mantenimiento')], default='activo', max_length=30)),
                ('fecha_revision_tecnica', models.DateField(blank=True, null=True)),
                ('last_latitude', models.FloatField(blank=True, null=True)),
                ('last_longitude', models.FloatField(blank=True, null=True)),
                ('last_reported_at', models.DateTimeField(blank=True, null=True)),
                ('estado_actual', models.CharField(blank=True, max_length=50)),
                ('colegio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='furgones', to='core.colegio')),
                ('conductor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='furgones', to='core.conductor')),
            ],
        ),
        migrations.CreateModel(
            name='Ruta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_ruta', models.CharField(choices=[('ida', 'Ida'), ('vuelta', 'Vuelta'), ('completa', 'Completa')], default='ida', max_length=20)),
                ('hora_inicio', models.TimeField(blank=True, null=True)),
                ('hora_termino', models.TimeField(blank=True, null=True)),
                ('furgon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rutas', to='core.furgon')),
            ],
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=8)),
                ('fecha', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('pagado', 'Pagado'), ('cancelado', 'Cancelado')], default='pendiente', max_length=20)),
                ('referencia', models.CharField(blank=True, max_length=255)),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='core.estudiante')),
            ],
        ),
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('info', 'Información'), ('alert', 'Alerta'), ('evento', 'Evento')], default='info', max_length=20)),
                ('mensaje', models.TextField()),
                ('creado_at', models.DateTimeField(auto_now_add=True)),
                ('leido', models.BooleanField(default=False)),
                ('estudiante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to='core.estudiante')),
                ('furgon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notificaciones', to='core.furgon')),
            ],
        ),
        migrations.AddField(
            model_name='estudiante',
            name='furgon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='estudiantes', to='core.furgon'),
        ),
        migrations.CreateModel(
            name='Asistencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('estado', models.CharField(choices=[('presente', 'Presente'), ('recogido', 'Recogido'), ('entregado', 'Entregado'), ('ausente', 'Ausente')], max_length=20)),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asistencias', to='core.estudiante')),
                ('furgon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asistencias', to='core.furgon')),
            ],
            options={
                'unique_together': {('estudiante', 'fecha')},
            },
        ),
    ]
