# Generated by Django 4.2 on 2025-11-25 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_conductor_user_estudiante_apoderado_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='ruta',
            name='localidades',
            field=models.CharField(blank=True, help_text='Lista de localidades / paradas separadas por comas', max_length=500),
        ),
    ]
